<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Service;

use Kei\Lwphp\Base\Service;
use Kei\Lwphp\Repository\CategoryRepository;
use Psr\Log\LoggerInterface;

class CategoryService extends Service
{
    public function __construct(
        private readonly CategoryRepository $repository,
        LoggerInterface $logger
    ) {
        parent::__construct($logger);
    }

    public function getAll(): array
    {
        return $this->repository->findAll();
    }

    public function getById(int $id)
    {
        return $this->repository->findById($id);
    }

    public function create(array $data)
    {
        return $this->execute(function () use ($data) {
            if (empty($data['name'])) {
                throw new \InvalidArgumentException('Category name is required.');
            }
            $entity = new \Kei\Lwphp\Entity\Category();
            $entity->setName($data['name']);
            $entity->setDescription($data['description'] ?? null);
            return $this->repository->save($entity);
        }, 'Create Category');
    }

    public function update(int $id, array $data)
    {
        return $this->execute(function () use ($id, $data) {
            if (empty($data['name'])) {
                throw new \InvalidArgumentException('Category name is required.');
            }
            $entity = $this->repository->findById($id);
            if (!$entity) {
                throw new \RuntimeException('Category not found');
            }
            $entity->setName($data['name']);
            $entity->setDescription($data['description'] ?? null);
            return $this->repository->save($entity);
        }, 'Update Category');
    }

    public function delete(int $id): bool
    {
        return $this->execute(function () use ($id) {
            return $this->repository->delete($id);
        }, 'Delete Category');
    }
}
