<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Service;

use Kei\Lwphp\Base\Service;
use Kei\Lwphp\Repository\LandingFeatureRepository;
use Psr\Log\LoggerInterface;

class LandingFeatureService extends Service
{
    public function __construct(
        private readonly LandingFeatureRepository $repository,
        LoggerInterface $logger
    ) {
        parent::__construct($logger);
    }

    public function getAll(): array
    {
        return $this->repository->findAll();
    }

    public function getById(int|string $id)
    {
        return $this->repository->findById($id);
    }

    public function create(array $data)
    {
        return $this->execute(function () use ($data) {
            if (empty($data['title']) || empty($data['description']) || empty($data['icon'])) {
                throw new \InvalidArgumentException('Title, description, and icon are required.');
            }
            $entity = new \Kei\Lwphp\Entity\LandingFeature();
            $entity->setTitle($data['title']);
            $entity->setDescription($data['description']);
            $entity->setIcon($data['icon']);
            return $this->repository->save($entity);
        }, 'Create LandingFeature');
    }

    public function update(int|string $id, array $data)
    {
        return $this->execute(function () use ($id, $data) {
            $entity = $this->repository->findById($id);
            if (!$entity) {
                throw new \RuntimeException('LandingFeature not found.');
            }
            if (isset($data['title']))
                $entity->setTitle($data['title']);
            if (isset($data['description']))
                $entity->setDescription($data['description']);
            if (isset($data['icon']))
                $entity->setIcon($data['icon']);
            return $this->repository->save($entity);
        }, 'Update LandingFeature');
    }

    public function delete(int|string $id): bool
    {
        return $this->execute(function () use ($id) {
            return $this->repository->delete($id);
        }, 'Delete LandingFeature');
    }
}
