<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Service;

use Kei\Lwphp\Base\Service;
use Kei\Lwphp\Repository\LandingFeatureRepository;
use Psr\Log\LoggerInterface;

class LandingFeatureService extends Service
{
    public function __construct(
        private readonly LandingFeatureRepository $repository,
        LoggerInterface $logger
    ) {
        parent::__construct($logger);
    }

    public function getAll(): array
    {
        return $this->repository->findAll();
    }

    public function getById(int $id)
    {
        return $this->repository->findById($id);
    }

    public function create(array $data)
    {
        return $this->execute(function () use ($data) {
            // Validate data, create entity, persist via repository
            // return $entity;
        }, 'Create LandingFeature');
    }

    public function update(int $id, array $data)
    {
        return $this->execute(function () use ($id, $data) {
            // Fetch entity, update fields, persist
            // return $entity;
        }, 'Update LandingFeature');
    }

    public function delete(int $id): bool
    {
        return $this->execute(function () use ($id) {
            return $this->repository->delete($id);
        }, 'Delete LandingFeature');
    }
}
