<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Service;

use Kei\Lwphp\Base\Service;
use Kei\Lwphp\Repository\TestimonialRepository;
use Psr\Log\LoggerInterface;

class TestimonialService extends Service
{
    public function __construct(
        private readonly TestimonialRepository $repository,
        LoggerInterface $logger
    ) {
        parent::__construct($logger);
    }

    public function getAll(): array
    {
        return $this->repository->findAll();
    }

    public function getById(int|string $id)
    {
        return $this->repository->findById($id);
    }

    public function create(array $data)
    {
        return $this->execute(function () use ($data) {
            if (empty($data['authorName']) || empty($data['content'])) {
                throw new \InvalidArgumentException('Author name and content are required.');
            }
            $entity = new \Kei\Lwphp\Entity\Testimonial();
            $entity->setAuthorName($data['authorName']);
            $entity->setCompany($data['company'] ?? null);
            $entity->setContent($data['content']);
            return $this->repository->save($entity);
        }, 'Create Testimonial');
    }

    public function update(int|string $id, array $data)
    {
        return $this->execute(function () use ($id, $data) {
            $entity = $this->repository->findById($id);
            if (!$entity) {
                throw new \RuntimeException('Testimonial not found.');
            }
            if (isset($data['authorName']))
                $entity->setAuthorName($data['authorName']);
            if (array_key_exists('company', $data))
                $entity->setCompany($data['company']);
            if (isset($data['content']))
                $entity->setContent($data['content']);
            return $this->repository->save($entity);
        }, 'Update Testimonial');
    }

    public function delete(int|string $id): bool
    {
        return $this->execute(function () use ($id) {
            return $this->repository->delete($id);
        }, 'Delete Testimonial');
    }
}
