<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Service;

use Kei\Lwphp\Base\Service;
use Kei\Lwphp\Repository\UnitRepository;
use Psr\Log\LoggerInterface;

class UnitService extends Service
{
    public function __construct(
        private readonly UnitRepository $repository,
        LoggerInterface $logger
    ) {
        parent::__construct($logger);
    }

    public function getAll(): array
    {
        return $this->repository->findAll();
    }

    public function getById(int $id)
    {
        return $this->repository->findById($id);
    }

    public function create(array $data)
    {
        return $this->execute(function () use ($data) {
            $entity = new \Kei\Lwphp\Entity\Unit();
            // Automatically map provided data to standard setters (e.g., 'title' -> 'setTitle')
            foreach ($data as $key => $val) {
                // Ignore structural UI keys like csrf_token
                if ($key === 'csrf_token') continue;
                $setter = 'set' . str_replace('_', '', ucwords($key, '_'));
                if (method_exists($entity, $setter)) {
                    $entity->$setter($val);
                }
            }
            return $this->repository->save($entity);
        }, 'Create Unit');
    }

    public function update(int $id, array $data)
    {
        return $this->execute(function () use ($id, $data) {
            $entity = $this->repository->findById($id);
            if (!$entity) {
                throw new \RuntimeException('Unit not found.');
            }
            foreach ($data as $key => $val) {
                if ($key === 'csrf_token' || $key === 'id') continue;
                $setter = 'set' . str_replace('_', '', ucwords($key, '_'));
                if (method_exists($entity, $setter)) {
                    $entity->$setter($val);
                }
            }
            return $this->repository->save($entity);
        }, 'Update Unit');
    }

    public function delete(int $id): bool
    {
        return $this->execute(function () use ($id) {
            return $this->repository->delete($id);
        }, 'Delete Unit');
    }
}
