<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Entity;

use Doctrine\ORM\Mapping as ORM;
use Kei\Lwphp\Base\Entity;

#[ORM\Entity]
#[ORM\Table(name: 'articles')]
class Article extends Entity
{
    #[ORM\Column(type: 'string', length: 255)]
    private string $title;

    #[ORM\Column(type: 'text')]
    private string $content;

    public function __construct()
    {
        parent::__construct();
        // Initialize collections or default values
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'title' => $this->title ?? '',
            'content' => $this->content ?? '',
            'created_at' => $this->createdAt->format(\DateTimeInterface::ATOM),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::ATOM),
        ];
    }
}