<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Entity;

use Doctrine\ORM\Mapping as ORM;
use Kei\Lwphp\Base\Entity;

#[ORM\Entity]
#[ORM\Table(name: 'categorys')]
class Category extends Entity
{
    #[ORM\Column(type: 'string', length: 255)]
    private string $name;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $description = null;

    public function __construct()
    {
        parent::__construct();
        // Initialize collections or default values
    }

    public function getName(): string
    {
        return $this->name;
    }
    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function setDescription(?string $desc): self
    {
        $this->description = $desc;
        return $this;
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name ?? '',
            'description' => $this->description ?? '',
            'created_at' => $this->createdAt->format(\DateTimeInterface::ATOM),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::ATOM),
        ];
    }
}
