<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Entity;

use Doctrine\ORM\Mapping as ORM;
use Kei\Lwphp\Base\Entity;

#[ORM\Entity]
#[ORM\Table(name: 'testimonials')]
class Testimonial extends Entity
{
    #[ORM\Column(type: 'string', length: 255)]
    private string $authorName;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $company = null;

    #[ORM\Column(type: 'text')]
    private string $content;

    public function __construct()
    {
        parent::__construct();
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'authorName' => $this->authorName,
            'company' => $this->company,
            'content' => $this->content,
            'created_at' => $this->createdAt->format(\DateTimeInterface::ATOM),
            'updated_at' => $this->updatedAt->format(\DateTimeInterface::ATOM),
        ];
    }

    public function getAuthorName(): string
    {
        return $this->authorName;
    }

    public function setAuthorName(string $authorName): void
    {
        $this->authorName = $authorName;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): void
    {
        $this->company = $company;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function setContent(string $content): void
    {
        $this->content = $content;
    }
}
