<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Repository;

use Kei\Lwphp\Base\Repository;
use Kei\Lwphp\Entity\Unit;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @extends Repository<Unit>
 */
class UnitRepository extends Repository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em);
    }

    protected function entityClass(): string
    {
        return Unit::class;
    }
}
