<?php

// phpcs:disable
// This file was auto-generated by LWPHP CLI

namespace Kei\Lwphp\Controller;

use Kei\Lwphp\Base\Controller;
use Kei\Lwphp\Service\SaleService;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;

class SaleController extends Controller
{
    public function __construct(
        private readonly SaleService $service
    ) {
        parent::__construct();
    }

    public function index(Request $request, array $args): Response
    {
        $items = $this->service->getAll(); 
        return $this->render('sales/index', ['items' => $items]);
    }

    public function feed(Request $request, array $args): Response
    {
        $items = $this->service->getAll(); 
        return $this->render('sales/feed', ['items' => $items]);
    }

    public function create(Request $request, array $args): Response
    {
        return $this->render('sales/form');
    }

    public function edit(Request $request, array $args): Response
    {
        $id = $args['id'] ?? 0;
        $item = $this->service->getById($id);

        if (!$item) {
            return $this->notFound('Sale', $id);
        }

        return $this->render('sales/form', ['item' => $item]);
    }

    public function store(Request $request, array $args): Response
    {
        $data = $this->parseBody($request);
        $this->service->create($data);
        
        // HTMX Refresh Header
        return $this->factory->createResponse(200)->withHeader('HX-Refresh', 'true');
    }

    public function update(Request $request, array $args): Response
    {
        $id = $args['id'] ?? 0;
        $data = $this->parseBody($request);
        $this->service->update($id, $data);
        
        return $this->factory->createResponse(200)->withHeader('HX-Refresh', 'true');
    }

    public function destroy(Request $request, array $args): Response
    {
        $id = $args['id'] ?? 0;
        $this->service->delete($id);
        
        return $this->factory->createResponse(200)->withHeader('HX-Refresh', 'true');
    }
}
