<?php

namespace Kei\Lwphp\Console;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\String\UnicodeString;

abstract class MakeCommand extends Command
{
    /**
     * Renders a stub file with the given variables.
     */
    protected function renderStub(string $stubName, array $vars): string
    {
        $stubPath = __DIR__ . '/Stubs/' . $stubName . '.stub';
        if (!file_exists($stubPath)) {
            throw new \RuntimeException("Stub file not found: $stubPath");
        }

        $content = file_get_contents($stubPath);
        foreach ($vars as $key => $value) {
            $content = str_replace('{{ ' . $key . ' }}', $value, $content);
        }

        return $content;
    }

    /**
     * Formats a string to PascalCase (e.g., user_profile -> UserProfile)
     */
    protected function toPascalCase(string $string): string
    {
        return (new UnicodeString($string))->camel()->title()->toString();
    }

    /**
     * Formats a string to camelCase (e.g., UserProfile -> userProfile)
     */
    protected function toCamelCase(string $string): string
    {
        return (new UnicodeString($string))->camel()->toString();
    }

    /**
     * Formats a string to snake_case (e.g., UserProfile -> user_profile)
     */
    protected function toSnakeCase(string $string): string
    {
        return (new UnicodeString($string))->snake()->toString();
    }

    /**
     * Writes content to a file, ensuring the directory exists and optionally skipping if file exists.
     * Appends a phpcs:disable flag to skip IDE formatter conflicts.
     */
    protected function writeClass(string $path, string $content, OutputInterface $output, bool $force = false): bool
    {
        if (file_exists($path) && !$force) {
            $output->writeln("<comment>Skipped:</comment> File already exists -> $path");
            return false;
        }

        $dir = dirname($path);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        // Add a signature to skip formatters
        $content = str_replace("<?php\n\n", "<?php\n\n// phpcs:disable\n// This file was auto-generated by LWPHP CLI\n\n", $content);

        file_put_contents($path, $content);
        $output->writeln("<info>Created:</info> $path");
        return true;
    }
}
